### ISSUE TITLE
Fix dep on Chef::Mixin::ShellOut

### ISSUE THREAD

**Issue by danielsdeleo** [chef/chef-config#4]
As used here: https://github.com/chef/chef-config/blob/beeabc1f6cb1966e18cb4bd23ed66eca6f5aff14/lib/chef-config/config.rb#L688

That's the only place it is used. We could have Chef reopen the class and add locale detection, maybe we could get away with just backticks, or we could try using `Process.spawn`, now that we only support ruby versions that include it.

**Comment by lamont-granquist** [comment]
i'm working on this one.
